/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <time.h>

void
add_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	intpair  add_1_arg;
	add_1_arg.a = 1;
	add_1_arg.b = 2;
#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Result received: %d\n", *result_1);
	clnt_destroy (clnt);
#ifndef	DEBUG
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[]){
	char *host;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	FILE *fp;
	fp = fopen("rpc_localhost.txt", "a+");
	host = argv[1];
	clock_t t; 
    	t = clock(); 
	add_prog_1 (host);
    	t = clock() - t; 
    	double time_taken = (((double)t)/CLOCKS_PER_SEC)*1000; // in seconds 
	printf("addrpc() took %f milliseconds to execute \n", time_taken); 
	fprintf(fp, "%f\n", time_taken);
	fclose(fp);
	exit (0);
}
