/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Tserv {
	u_long sec;
	u_long nsec;
};
typedef struct Tserv Tserv;

#define RPC_PROG 0x23451111
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RPC 1
extern  struct Tserv * rpc_1(void *, CLIENT *);
extern  struct Tserv * rpc_1_svc(void *, struct svc_req *);
extern int rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPC 1
extern  struct Tserv * rpc_1();
extern  struct Tserv * rpc_1_svc();
extern int rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Tserv (XDR *, Tserv*);

#else /* K&R C */
extern bool_t xdr_Tserv ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
