/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

struct Tserv *
rpc_1_svc(void *argp, struct svc_req *rqstp)
{
	static struct Tserv  result;

	/*
	 * insert server code here
	 */

	return &result;
}
