/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_Tserv (XDR *xdrs, Tserv *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->sec))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->nsec))
		 return FALSE;
	return TRUE;
}
