/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include<time.h>
struct Tserv *
rpc_1_svc(void *argp, struct svc_req *rqstp)
{
	static struct Tserv  result;

	struct timespec t_server;
        clock_gettime(CLOCK_REALTIME, &t_server);
	//write(0, "Server boi active\n", 19);
	result.nsec = t_server.tv_nsec;
	result.sec = t_server.tv_sec;
	return &result;
}
