/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#define _POSIX_C_SOURCE 200809L
#include<stdio.h>
#include "add.h"
#include <time.h>

void
add_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	intpair  add_1_arg;
	add_1_arg.a = 1;
	add_1_arg.b = 2;
#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Result received: %d\n", *result_1);
	clnt_destroy (clnt);
#ifndef	DEBUG
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[]){
	struct timespec start, stop, result;
	char *host;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	FILE *fp;
	fp = fopen("rpc_localhost.txt", "a+");
	host = argv[1];
	clock_gettime(CLOCK_REALTIME, &start);
	//add_prog_1 (host);
	clock_gettime(CLOCK_REALTIME, &stop);
	if ((stop.tv_nsec - start.tv_nsec) < 0) {
        	result.tv_sec = stop.tv_sec - start.tv_sec - 1;
        	result.tv_nsec = stop.tv_nsec - start.tv_nsec + 1000000000;
    	} else {
         	result.tv_sec = stop.tv_sec - start.tv_sec;
        	result.tv_nsec = stop.tv_nsec - start.tv_nsec;
    	}	
	printf("addrpc() took %ld . %ld milliseconds to execute \n", result.tv_sec, result.tv_nsec); 
	fprintf(fp, "%ld . %ld \n", result.tv_sec, result.tv_nsec);
	fclose(fp);
	exit (0);
}
